### ISSUE TITLE
Add UI for switching map layers

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/digitransit-ui#103]
We would like to add a UI for switching between the map types in this component:

![Screenshot from 2020-03-26 11-09-06](https://user-images.githubusercontent.com/151346/77640805-49dabb00-6f5b-11ea-8c76-10bc7476093b.png)

The new UI should be a new section at the bottom with two radio buttons (not checkboxes) where you can select one of these items:

- Straßen/Streets (the current default layer)
- Satellit/Satellite (new layer)

I would love it if we can skip the store approach that I suggested previously and could make it work with URL params instead.

Please investigate if it's possible.

If it is possible use the following URL params:

`mapMode=default` (or nothing)
`mapMode=satellite`

which means we can add a `mapMode=bicyle` later.

## Attribution

When switching the map mode, also change the attribution in the bottom right corner.

For satellite use:

```
© <a tabindex=-1 href=http://osm.org/copyright>OpenStreetMap Mitwirkende</a>, © Baden-Württemberg Luftbilder, © <a tabindex=-1 href="https://www.maptiler.com/copyright/">Maptiler</a>, <a tabindex=-1 href=https://www.nvbw.de/aufgaben/digitale-mobilitaet/open-data/>Datensätze der NVBW GmbH</a> und <a tabindex=-1 href=https://www.openvvs.de/dataset/gtfs-daten>VVS GmbH</a>
```

## Miscellaneous

- Remove everything to do with the map key
- Remove the `isSatellite` function

**Comment by meromisi** [comment]
looks like this so far 
![image](https://user-images.githubusercontent.com/54352878/77644807-f61fa000-6f61-11ea-91ab-8a94a0385639.png)
