### ISSUE TITLE
Investigate why attribution is not updated with the rest of the map

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/digitransit-ui#108]
Right now the attribution doesn't update even when the map properties change. Because of this, I've hardcoded all the attributions to be the same but this is obviously not what we want.

Investigate why this doesn't work. I suspect a library bug in `react-leaflet`.

Try if it makes a difference when you upgrade the library to the newest version.

**Comment by Beck-berry** [comment]
Updated Leaflet to version 2.1.4 and installed all missing dependencies (npm found some vulnerabilities which could be fix with an `npm install`). Update caused an error in the server.js, at the usage of the polyfillLibrary, which needed a small modification.
After the update I did not notice any changes in the behaviour - the attribute still not updates.
