### ISSUE TITLE
Review eslint warnings

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/digitransit-ui#110]
We have thousands of warnings and are ignoring them. This means there is no point in having them.

Acceptance criteria:

- Look at .eslintrc.js
- Check all the rules with the word `warn` in them
- For each rule decide if it is worth having
  - If it's not useful, comment out the line
  - If it's useful, set it to error and fix all the issues

**Comment by Beck-berry** [comment]
If we comment out a line, eslint will consider the missing rule to be an error. I'll use 'off' instead.
