### ISSUE TITLE
Investigate how to draw custom map Icons with different "rings" around them

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/digitransit-ui#121]
This is a follow up on #120.

https://github.com/osmontrouge/caresteouvert/tree/master/mapicons contains map icons for the Covid-19 opening hours layer.

We would also like to use the same visual representation as bleibtoffen.de:

![Screenshot from 2020-04-14 22-04-13](https://user-images.githubusercontent.com/151346/79269016-0c06ed80-7e9c-11ea-9bee-cc07db37d057.png)

Acceptance criteria:

- Draw custom map icon onto map
- Add white circle around it
- Add grey/red/green ring depending on opening hours status

I took a quick glance around the icons code and I could not find anything that satisfies all these needs, so it's likely that we have to write it ourselves.

**Comment by Beck-berry** [comment]
![Screenshot_2020-04-16_09-52-14](https://user-images.githubusercontent.com/46535522/79429578-f8f13c00-7fc7-11ea-90bc-e876d85cbeb3.png)
