### ISSUE TITLE
Translate POI category in Covid-19 popup

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/digitransit-ui#125]
Each POI has a property `cat` and `normalized_cat`. At the moment these are placed as is into the UI.

![Screenshot from 2020-04-15 15-24-46](https://user-images.githubusercontent.com/151346/79343128-4faa3780-7f2e-11ea-978e-0722186ee7f4.png)

An example of the source data is available here: https://features.caresteouvert.fr/collections/public.poi_osm/items/n1826763397.json

Acceptance criteria:

- Check out the existing translations from resteouvert: https://github.com/osmontrouge/caresteouvert/blob/master/locales/de.json#L141-L199 (English version should be in the same repo)
- Copy them into `translations.js` and use the prefix `poi-`, so `bakery` becomes `poi-bakery`. This makes it easier to add them to the file and also to find all the categories later.
- Use the translated categories in the popup.

Note: Investigate if there's a difference between `cat` and `normalized_cat`. The later sounds like what we want, but check.

**Comment by Beck-berry** [comment]
Here are a few examples of `cat` - `normalized_cat` pairs:
fast_food eat 
pharmacy health 
restaurant eat 
hearing_aids health 
insurance amenity 
supermarket food 
optician health 
grocery food 
alcohol drugs 
cheese food 
fabric shop
bakery food
convenience food 
butcher food 
books shop 
ice_cream eat 
marketplace food 
newsagent shop 
chemist chemist 
bank amenity 

Seems `cat` is a bit more precise. In the translations file there are translations for both type. Which one to use?

**Comment by leonardehrenfried** [comment]
If we have translations for both, then I would prefer the more precise `cat`.
