### ISSUE TITLE
Wrong bicycle routing: detour avoiding Erhardtstraße

### ISSUE THREAD

**Issue by hbruch** [mfdz/digitransit-ui#127]
Bicycle routing avoids Erhardtstraße, instead of routing straight through, a large detour is returned:
https://herrenberg.stadtnavi.de/reitti/Erhardtstraße%2015%2C%2071083%20Herrenberg%3A%3A48.59245535589966%2C8.868091106414797/Marienstraße%209%2C%2071083%20Herrenberg%3A%3A48.593250120269296%2C8.872570395469667?mapMode=bicycle&modes=BICYCLE&time=1586978981

Possibly related to oneway attribution, at least the last change commit cites, a former oneway restriction was recently removed:
https://www.openstreetmap.org/way/740740293

Experimenting with start/stop position, It looks to me like Erhardtstraße is considered destination only, though I don't see any tags or relations that support this.

**Comment by leonardehrenfried** [comment]
It seems like it's not Erhardstr. that is the problem: 

https://mih.mitfahren-bw.de/reitti/Erhardtstra%C3%9Fe%2015%2C%2071083%20Herrenberg%3A%3A48.59245535589966%2C8.868091106414797/Markusstra%C3%9Fe%208%2C%2071083%20Herrenberg%3A%3A48.593360996001266%2C8.872357830405237?debugTiles&modes=BICYCLE&time=1586978981

but rather the crossing on Markusstr/Marienstr:

https://mih.mitfahren-bw.de/reitti/Erhardtstra%C3%9Fe%2015%2C%2071083%20Herrenberg%3A%3A48.59245535589966%2C8.868091106414797/Markusstra%C3%9Fe%2C%2071083%20Herrenberg%3A%3A48.59342752132367%2C8.87251138687134?debugTiles&modes=BICYCLE&time=1586978981

**Comment by leonardehrenfried** [comment]
Interestingly, if you set it to "avoid evevation distance" it works as expected: https://mih.mitfahren-bw.de/reitti/Erhardtstra%C3%9Fe%2022%2C%2071083%20Herrenberg%3A%3A48.59219989326873%2C8.866621255874636/Marienstra%C3%9Fe%209%2C%2071083%20Herrenberg%3A%3A48.59322883210091%2C8.872591853141786?accessibilityOption=0&bikeSpeed=5&minTransferTime=120&modes=BICYCLE&optimize=TRIANGLE&safetyFactor=0.1&slopeFactor=0.8&ticketTypes&time=1586978981&timeFactor=0.1&transferPenalty=0&walkBoardCost=600&walkReluctance=2&walkSpeed=1.2

So, my very brief analysis is that it's to do with the WayPropertySet.

After the Covid-19 feature I will look into it in more detail.

**Comment by leonardehrenfried** [comment]
![Screenshot from 2020-04-17 11-32-17](https://user-images.githubusercontent.com/151346/79555228-88b5e980-809f-11ea-8c29-e42a9d34fae6.png)

If I use the default WayPropertySet, it behaves as expected.
