### ISSUE TITLE
Bug: Cannot open POI details when they are too close to each other

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/digitransit-ui#130]
Weirdly, digitransit only allows you to open a popup when there is only a single click target.

Check `TileLayerContainer`.

I would say that if there are more than one candidate, open the top one. If the user wants another one she has to zoom in.

**Comment by leonardehrenfried** [comment]
Actually, you need to implement a selector row so that you can choose from several options.

**Comment by leonardehrenfried** [comment]
So, I've hooked into the ordinary mechanism for choosing from several options. Unfortunately this results in a somewhat confusing experience:

![Screenshot from 2020-04-16 15-46-22](https://user-images.githubusercontent.com/151346/79463857-aa5c9580-7ff9-11ea-900d-37dfdb8e831e.png)

What we definitely want is to add the icon in this view.

Perhaps we also need to make this component more customisable.

@hbruch Do you have an opinion?

**Comment by hbruch** [comment]
Generalizing the component makes sense. We should show the icon, change „Choose stop“ to something generic. Where comes the green link color from? Is it the stadtnavi color or  carpooling stop? I‘d prefer black.

**Comment by Beck-berry** [comment]
Green was the stadtnavi $link-color.

![Screenshot_2020-04-17_09-35-04](https://user-images.githubusercontent.com/46535522/79546203-4d60ee00-8092-11ea-8330-b7b9393ecc42.png)

**Comment by leonardehrenfried** [comment]
Closed by #134
