### ISSUE TITLE
Covid-19: Deliveries and takeout

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/digitransit-ui#131]
Add the information about deliveries and takeout to the popup.

Example data: https://features.caresteouvert.fr/collections/public.poi_osm/items/n7017438374.json

This is how bleibt-offen visualises it.

![Screenshot from 2020-04-16 11-17-05](https://user-images.githubusercontent.com/151346/79438488-dcf39780-7fd3-11ea-8404-160e8626c369.png)

**Comment by Beck-berry** [comment]
There are two delivery properties: one is the `properties.delivery`, other is the `properties.tags.delivery:covid19`. Can we assume that if a facility offers delivery normally then it is valid for the covid situation too (and use the default delivery as a fallback if it's not specified in the tags for covid)?

**Comment by leonardehrenfried** [comment]
> There are two delivery properties: one is the `properties.delivery`, other is the `properties.tags.delivery:covid19`. Can we assume that if a facility offers delivery normally then it is valid for the covid situation too (and use the default delivery as a fallback if it's not specified in the tags for covid)?

Absolutely.
