### ISSUE TITLE
Add new icons and english translations

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/digitransit-ui#135]
Ca reste ouvert has added more cateogories and icons: https://github.com/osmontrouge/caresteouvert/commit/af20861bdb0d529435f0b2b8810b60e747054e06

Acceptance criteria:
- Copy new icons
- Copy english translations

German translations don't seem to be there yet, so I will add them myself.

**Comment by hbruch** [comment]
If possible, please do a PR to caresteouvert, too. Or have look at bleibtoffen, if somebody is already working on it.

**Comment by leonardehrenfried** [comment]
I have added the translations to their translation tool Transifex.
