### ISSUE TITLE
Replace bus sign at high zoom with a logo

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/digitransit-ui#139]
A user has said that the red dot look like "no through traffic" sign and we would like to see how it would look like if we used a logo.

Acceptance criteria:

- Replace the white dot with red circle on a high zoom level with the following SVG: https://upload.wikimedia.org/wikipedia/commons/6/6d/Bus-Logo_VVS.svg
- Use your best judgment about what "high" means. We definitely don't want to have a super busy map like this: 

![Screenshot_2020-04-16-15-18-02 png](https://user-images.githubusercontent.com/151346/79668936-767b9e80-81b8-11ea-9507-3a152afffc0c.jpg)

**Comment by Beck-berry** [comment]
I tried to look for a place where the map is more busy... Finally I took screenshots in Stuttgart.
Right now the bus icon displays on map when the zoom is at 100m.

![Screenshot_2020-04-24_09-04-34](https://user-images.githubusercontent.com/46535522/80184425-d932c700-860a-11ea-9c06-c46d6f8849f5.png)
![Screenshot_2020-04-24_09-04-53](https://user-images.githubusercontent.com/46535522/80184428-da63f400-860a-11ea-8db1-f6fc892fb87d.png)

**Comment by leonardehrenfried** [comment]
Whilst I preferred the old way, to me that looks ok.

@hbruch What do you think?

**Comment by leonardehrenfried** [comment]
New PR: #160

**Comment by Beck-berry** [comment]
![Screenshot_2020-05-05_09-35-00](https://user-images.githubusercontent.com/46535522/81044730-2dfcfa00-8eb5-11ea-95e7-3e2547824743.png)
![Screenshot_2020-05-05_09-35-21](https://user-images.githubusercontent.com/46535522/81044738-2f2e2700-8eb5-11ea-939e-bc07862f0ccb.png)
