### ISSUE TITLE
Make it more clear that you can edit on bleibtoffen.de

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/digitransit-ui#144]
In the Covid popup it says "Source: bleibtoffen.de".

We would like to make it more clear that you can edit as well.

Therefore we should make this a button which says

- Edit on bleibtoffen.de
- Auf bleibtoffen.de bearbeiten

**Comment by Beck-berry** [comment]
![Screenshot_2020-04-22_10-06-58](https://user-images.githubusercontent.com/46535522/79956879-094e5e80-8481-11ea-80bf-9e836f5643e1.png)

**Comment by leonardehrenfried** [comment]
Is there a smaller button style?

**Comment by Beck-berry** [comment]
Not really. I can write a custom style if you want me to.

**Comment by hbruch** [comment]
Could you check out the CallAgencyLeg or so? Digitransit usually uses rounded buttons, we should stay in line with these

**Comment by Beck-berry** [comment]
![Screenshot_2020-04-22_10-31-55](https://user-images.githubusercontent.com/46535522/79959524-83ccad80-8484-11ea-9449-c56684b381e6.png)

**Comment by leonardehrenfried** [comment]
Yes, but can you remove the `<a>`. I think that's why we see the blue font colour.

**Comment by Beck-berry** [comment]
![Screenshot_2020-04-22_10-50-41](https://user-images.githubusercontent.com/46535522/79961651-4fa6bc00-8487-11ea-8a5a-abdd3040f0b1.png)

**Comment by leonardehrenfried** [comment]
Can you make it look like this?

![Screenshot from 2020-04-22 11-00-26](https://user-images.githubusercontent.com/151346/79962598-87faca00-8488-11ea-8ec6-c810b0220972.png)

**Comment by Beck-berry** [comment]
![Screenshot_2020-04-22_11-01-35](https://user-images.githubusercontent.com/46535522/79962684-a5c82f00-8488-11ea-801b-f6d55c632c12.png)

**Comment by leonardehrenfried** [comment]
Looks good. Now we just it to be in the middle.

**Comment by Beck-berry** [comment]
![Screenshot_2020-04-22_11-28-03](https://user-images.githubusercontent.com/46535522/79965476-5b48b180-848c-11ea-8a8d-dd0099817300.png)

**Comment by leonardehrenfried** [comment]
:pray:
