### ISSUE TITLE
Merge all the latest changes from upstream

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/digitransit-ui#145]
We have not rebased or merged the changes from upstream (HSLdev/digitransit-ui) for a while but we should not divert too much.

Please merge all the recent changes, resolve the conflicts and then test the application thoroughly.

**Comment by meromisi** [comment]
Okay, I rebased it(took a long time since it was more than 500 commits) and it totally broke the application, on friday I will investigate how to solve it. The branch I was working on is follow-upstream.
