### ISSUE TITLE
Add destination/origin buttons for Covid popup

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/digitransit-ui#146]
It should look like the rest., ie.

![Screenshot from 2020-04-22 11-23-45](https://user-images.githubusercontent.com/151346/79964975-bded7d80-848b-11ea-97ee-9d00626ed43a.png)

**Comment by Beck-berry** [comment]
May I also do the same for the dynamic parking lots popup?

**Comment by leonardehrenfried** [comment]
Yes, please.

**Comment by Beck-berry** [comment]
It is already added to dynamic parking lots, I just typed before checking :sweat_smile:
