### ISSUE TITLE
Fix newsagent icon

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/digitransit-ui#149]
It's pulled a little to the top left.

![Screenshot from 2020-04-22 13-02-38](https://user-images.githubusercontent.com/151346/79974416-99000700-8499-11ea-95aa-86d7bab870be.png)

Same for the TV:

![Screenshot from 2020-04-22 13-03-46](https://user-images.githubusercontent.com/151346/79974501-bb922000-8499-11ea-84d0-4559f5df0f0c.png)

**Comment by Beck-berry** [comment]
[Created PR](https://github.com/osmontrouge/caresteouvert/pull/516) according to this issue.

**Comment by leonardehrenfried** [comment]
Lovely. Let's see what they say.

**Comment by leonardehrenfried** [comment]
They merged the PR already. That was quick!

Not sure if there is more left to do, but can you run the import script one more time and check if there is a difference?
