### ISSUE TITLE
Discuss with upstream if they are willing to split translation.js into several files

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/digitransit-ui#156]
`translations.js` is huge and quite hard to navigate. The largeness of the file makes it also hard write scripts that operate on it.

We should ask upstream if they would be willing to merge a PR that splits it into several files - one for each language.

If they are ok with it, please create the PR and eventually we will get the change in our DT, too.

**Comment by Beck-berry** [comment]
I submitted the idea as a [new issue](https://github.com/HSLdevcom/digitransit-ui/issues/3222).

**Comment by leonardehrenfried** [comment]
They haven't answered yet so I would just make a speculative PR upstream.

**Comment by Beck-berry** [comment]
Raised a [PR](https://github.com/HSLdevcom/digitransit-ui/pull/3226).

**Comment by leonardehrenfried** [comment]
Please check that the newly added JSON files are covered by eslint (change the alphabetical order) and if they aren't configure the plugin mentioned in the upstream PR.
