### ISSUE TITLE
Take status open_adapted into account

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/digitransit-ui#158]
The cheese shop in Herrenberg has the status `open_adapted`.

![Screenshot from 2020-04-28 14-53-59](https://user-images.githubusercontent.com/151346/80489502-335fbf00-8960-11ea-957e-9ab26dd06cf7.png)

We should give this a green ring and use the message "covid-19-partial".

**Comment by Beck-berry** [comment]
![Screenshot_2020-04-29_10-56-00](https://user-images.githubusercontent.com/46535522/80577947-09fa6e00-8a08-11ea-996b-c09d69b912ce.png)
