### ISSUE TITLE
Departure display shows the next station as the trip_headsign

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/digitransit-ui#165]
![Screenshot from 2020-05-03 21-55-24](https://user-images.githubusercontent.com/151346/80924380-da8d8d80-8d88-11ea-8b14-d3320f15afcb.png)

**Comment by leonardehrenfried** [comment]
Doesn't seem to be the case with the new feed anymore. :man_shrugging:

**Comment by leonardehrenfried** [comment]
![Screenshot from 2020-05-04 15-10-24](https://user-images.githubusercontent.com/151346/80969130-65b66400-8e19-11ea-9f4f-0488e9038ff7.png)

**Comment by hbruch** [comment]
Yes. Was an issue with the NVBW data. Might probably still be the case for Naldo and vgc feed data.
