### ISSUE TITLE
Investigate missing translation in departure table

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/digitransit-ui#166]
The text in the dropdown contains some mistranslated string. Not sure why it should even contain a translation at all.

![Screenshot from 2020-05-04 15-28-53](https://user-images.githubusercontent.com/151346/80970762-f9892f80-8e1b-11ea-8ad1-3bc977559554.png)

URL to check: https://mih.mitfahren-bw.de/routen/hbg:31-775-j20-1/haltestellen/hbg:31-775-j20-1:1:04?sort=no

Check if this is also broken upstream and if it is, send a bugfix PR.

**Comment by Beck-berry** [comment]
The translations are in the `helpers/translations.js` file and originally there is English, Finnish and Swedish translations given. This is why the German does not work.

**Comment by leonardehrenfried** [comment]
I see. Can we fix it?

Is you post the strings here I can translate them.

**Comment by Beck-berry** [comment]
It is easy, only names of days :) I used three letters as it was done in English. If there's something you'd like me to change:
```
de: {
    'route-pattern-select-from': ' ({{range}} bis {{day}})',
    'route-pattern-select-only': 'nur ',
    'route-pattern-select-range-': ' ',
    'route-pattern-select-range--': ' ',
    'route-pattern-select-range-ke-ke': ' (Mit)',
    'route-pattern-select-range-la-la': ' (Sam)',
    'route-pattern-select-range-la-su': ' (Sam-Son)',
    'route-pattern-select-range-ma-la': ' (Mon-Sam)',
    'route-pattern-select-range-ma-ma': ' (Mon)',
    'route-pattern-select-range-ma-pe': ' (Mon-Fre)',
    'route-pattern-select-range-ma-su': ' ',
    'route-pattern-select-range-pe-la': ' (Fre-Sam)',
    'route-pattern-select-range-pe-pe': ' (Fre)',
    'route-pattern-select-range-pe-su': ' (Fre-Son)',
    'route-pattern-select-range-su-pe': ' (Mon-Fre und Son)',
    'route-pattern-select-range-su-su': ' (Son)',
    'route-pattern-select-range-ti-ti': ' (Die)',
    'route-pattern-select-range-to-to': ' (Don)',
    'route-pattern-select-range-undefined': ' ',
    'route-pattern-select-until': ' ({{range}} bis {{day}})',
  },
```

But adding the translations did not solve the problem so now I'm investigating why.

**Comment by Beck-berry** [comment]
So the German language were missing from the `@digitransit-util` node module.

**Comment by leonardehrenfried** [comment]
Since it looks broken for us, first fix it for us then send a PR.

In Germany we somehow only use two letters to abbreviate a day so it should be "(Fr - So)" not "(Fre - Son)". Not clue why.

**Comment by Beck-berry** [comment]
![Screenshot_2020-05-07_07-58-53](https://user-images.githubusercontent.com/46535522/81259639-a50ecb80-9038-11ea-918c-19fab77c4e87.png)
