### ISSUE TITLE
Add bike safety tiles

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/digitransit-ui#169]
We have the traversal permission tiles (Example: https://mih.mitfahren-bw.de/?debugTiles) that show you which modes can use a specific street.

There are more hidden debug tiles, specifically one for bicycle safety.

Acceptance criteria
- Add another URL param `bikeSafety`
- If either of those is set then display the following tiles: `${config.URL.OTP}inspector/tile/bike-safety/{z}/{x}/{y}.png`

**Comment by hbruch** [comment]
Would be great to have this upstream as well. Do we need the added complexity if having two names for the same layer?

**Comment by leonardehrenfried** [comment]
Since we have switchable URLs we modified Maps.js quiet heavily and we would have to basically do it twice. Are you ok with the extra effort?

I thought that we could use both names so you don't have to remember which one it is.

**Comment by hbruch** [comment]
Introducing name tolerance here will introduce name ambiguity which will haunt as at places, where only a single writing is supported. I'd stick to one of them. 
Concerning upstream PR: Are the Maps.js modifications backward compatible?

**Comment by leonardehrenfried** [comment]
Ok, fair enough.

Sadly they are not since we are passing in complete leaflet tile URLs whilst before we passed only the prefix and Maps.js added the rest. This was messy when the maptiler API keys had to be added so we went with full URLs.
