### ISSUE TITLE
COVID19-Layer: Wrong rendering for takeaway cafe

### ISSUE THREAD

**Issue by hbruch** [mfdz/digitransit-ui#171]
Café https://www.openstreetmap.org/node/4455051600 is open from 9am to 12pm, has access:covid19 no (you may not enter or sit there), but takeaway:covid19 true 

However, it is rendered as closed.

<img width="319" alt="image" src="https://user-images.githubusercontent.com/2187389/81113680-ed3aca80-8f20-11ea-97fc-21f9d09f5fe8.png">

By the way, takeaway should better be translated as "Mitnahme möglich" or, as bleibtoffen translates, as "Abholung möglich".

**Comment by leonardehrenfried** [comment]
The tag opening_hours:Covid-19 is set to "open". Presumably that means the same as the normal ones.

**Comment by Beck-berry** [comment]
All the other locations contains real opening hours in property `opening_hours` but this one has the string `"open"`. This is why the opening hours are not displayed (they are in the `tags.opening_hours` property).
![Screenshot_2020-05-07_12-53-45](https://user-images.githubusercontent.com/46535522/81286792-ec5d8200-9061-11ea-89ba-b2225cbe462b.png)

**Comment by leonardehrenfried** [comment]
So if it is `open` then use the ordinary ones.
