### ISSUE TITLE
Loading or resetting settings leads to failure to calculate bike routes

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/digitransit-ui#173]
When you load or reset the setting in the preferences panel, then invalid triangle factors are being sent to the server.

![Screenshot from 2020-05-06 14-28-23](https://user-images.githubusercontent.com/151346/81176802-fa4dcd00-8fa5-11ea-9fb9-35bc4e22de4d.png)

Steps to reproduce:

- Open an incognito window to make sure that no local storage has been set yet
- Open stadtnavi
- Start a bike search
- Open the settings panel
![Screenshot from 2020-05-06 14-35-54](https://user-images.githubusercontent.com/151346/81177498-0d14d180-8fa7-11ea-8f77-63ec47794f7a.png)
- Scroll to the bottom and click "Reset settings" or "Load settings"
- Notice the routing error. This is because there are no triangleFactors being send to the server
![Screenshot from 2020-05-06 14-37-50](https://user-images.githubusercontent.com/151346/81177704-654bd380-8fa7-11ea-92ab-7a86cd9f6635.png)

**Comment by Beck-berry** [comment]
If there is no customized settings, 
```js
const defaultSettings = getDefaultSettings(this.context.config);
const getSettings = getCustomizedSettings();
if (isEmpty(getSettings) || isEqual(getSettings, defaultSettings)) {
    this.props.noSettingsFound();
}
```
a function will run which removes the query params.
```js
resetParameters = () => {
    resetCustomizedSettings();
    clearQueryParams(this.context.router, Object.keys(this.defaultSettings));
};
```
All the factors are set correctly in the `this.defaultSettings`, but `clearQueryParams` will omit them. 
Replace it with `replaceQueryParams(this.context.router, paramsToClear);` seems to solve this issue but the `mapMode` remains the lastly chosen one. Is that a problem? Should it also reset to the default map?


Also the same error occurs when disable the selection of both routing preferences. (So this comes next. )
![Screenshot_2020-05-07_09-56-39](https://user-images.githubusercontent.com/46535522/81269052-1191c680-9049-11ea-8db2-a8286182e8d2.png)

**Comment by leonardehrenfried** [comment]
Map mode can stay.

In the long run we want to return several bike routes at the same time so the user doesn't have to select a profile and hopefully this mess goes away.

For this reason you can also remove the "Route preferences" so we don't waste time fixing something that isn't going to stay.
