### ISSUE TITLE
Remove "next" column also from box in start page

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/digitransit-ui#184]
The start page also contains a list of departures:

![image](https://user-images.githubusercontent.com/151346/81601994-20bba000-93cc-11ea-82a6-8309db688ac1.png)

Folllowing up on #167 this should be removed with the same config option, too.

You should send an upstream PR for this and if it gets merged quickly we can then get it into our repo.

**Comment by Beck-berry** [comment]
Please check out commit 26151166, then I'll raise a PR.

Screenshots:
![Screenshot_2020-05-12_09-47-42](https://user-images.githubusercontent.com/46535522/81655208-5b5a2280-9436-11ea-8dd5-451854ab98e5.png)
![Screenshot_2020-05-12_09-48-19](https://user-images.githubusercontent.com/46535522/81655213-5bf2b900-9436-11ea-9942-b9092946cb08.png)

**Comment by leonardehrenfried** [comment]
Hmm, is there a way around this `eslint-disable-next-line no-nested-ternary`, ie. could you rewrite that part of the code so it's a little easier to understand?

**Comment by Beck-berry** [comment]
Fixed: 8a689111

**Comment by leonardehrenfried** [comment]
Ok, please make a PR.

**Comment by Beck-berry** [comment]
[Here it is](https://github.com/HSLdevcom/digitransit-ui/pull/3245).

**Comment by leonardehrenfried** [comment]
Ok, upstream has merged so lets pull it back into our repo.
