### ISSUE TITLE
Keep satellite map mode even when clicking on a departure board or the start page

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/digitransit-ui#185]
A user has observer that the mapMode vanishes when you click on the top left Stadtnavi logo or when you view a departure board.

Steps to reproduce:
- Open Stadtnavi
- Switch to satellite mode
- Click on top left logo
- See that the map switches back to streets mode
- Switch to satellite again
- Then click on a train station and select a train line
- There the map mode is back to streets again.

We should at least think about if we would like to use a store instead of the URL. I have not fully thought through the advantages and disadvantages though so lets investigate how hard that would be to combine with the URL approach.

**Comment by Beck-berry** [comment]
I added a new store in commit c369a3cf, which would be the base for the `MapModeStore`, but I'm not sure how and when exactly to use it. I'll have to check on stores and then we can use this method if you'd like. It also can done via query params, I think, but there must be more little parts of the UI when we do not check the `mapMode`, those should be found and handled one by one - so maybe a store would be a better solution.

I fixed the the click on the logo: 2808cf66, so the `mapMode` param is given (even when default).
