### ISSUE TITLE
Configure husky to lint the translations before committing

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/digitransit-ui#190]
If this works for us we can think of sending a PR upstream.

**Comment by meromisi** [comment]
Problem is jsonlint lint doesn't throw any errors when the json file is not sorted and pre-commit hooks only fail when any number but 0 is thrown. Now it works like this: commit passes without json files are being sorted -> json files are being sorted -> you have uncommited changes (the sorted json files)

**Comment by leonardehrenfried** [comment]
So when you modify the a file during the hook, it will not be committed because it takes the state from before the hook?

**Comment by meromisi** [comment]
exactly

**Comment by meromisi** [comment]
modifications are not committed, unfortunately

**Comment by leonardehrenfried** [comment]
Ok, then leave it like that and also add it to the `run` script. This will increase the chance of the translations being sorted before the commit.
