### ISSUE TITLE
Configure Github Actions to run unit tests and linter for PRs

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/digitransit-ui#195]
Travis has stopped sending notifications for PRs for a while. I complained to customer support but no response so far.

I would like to try out Github Actions for PRs as I find the notifications very useful.

Acceptance criteria:

- Look at https://github.com/systemed/tilemaker/pull/158 how I added Github actions there
- Copy the file into our repo and run the commands we need.
- Check if there are nodejs 10 base images and use them.
- Leave `.travis.yml` in place

**Comment by Beck-berry** [comment]
Based on your example and the official documentation, I came up with this: commit 337dbe94 . I tested locally with [act](https://github.com/nektos/act) and constantly got the error: `An unexpected error occurred: "Failed to replace env in config: ${{ inputs.auth-token }".` I did not found any solution, do you have a suggestion?

**Comment by leonardehrenfried** [comment]
Not sure how act works exactly. Can you open a PR and I try it out?

**Comment by Beck-berry** [comment]
Seems like the problem really was with act, GitHub ran the yarn commands without error.
I might send them an issue to get to know what I messed up when running it :sweat_smile:

**Comment by leonardehrenfried** [comment]
Yes, please go ahead with this.
