### ISSUE TITLE
Run OTP locally

### ISSUE THREAD

**Issue by meromisi** [mfdz/digitransit-ui#28]
- figure out how URLs are configured
- make appropriate changes in configuration file to be able to run OTP locally
- [HSLdevcom/OTP repository](https://github.com/HSLdevcom/OpenTripPlanner)
  - [Basic Tutorial](https://opentripplanner.readthedocs.io/en/latest/Basic-Tutorial/)
- [use GTFS](https://openvvs.de/dataset/gtfs-daten)
- [download OpenStreetMap data](http://download.geofabrik.de/europe/germany/baden-wuerttemberg/stuttgart-regbez.html)

[OTP Tutorial](https://gis.stackexchange.com/questions/168054/open-trip-planner-tutorial)

[Run OTP in IntelliJ](https://github.com/opentripplanner/OpenTripPlanner/wiki/Setting-up-a-development-environment-in-IntelliJ-IDEA)

[OTP resources](http://dev.opentripplanner.org/apidoc/1.4.0/index.html#resources)

**Comment by Beck-berry** [comment]
### 1. Download all data into the same folder:
* newest OTP version (1.4.0)
* GTFS: VVS
* OpenStreetMap: Stuttgart area

### 2. Configure OSM into smaller Herrenberg area:
```
$ osmconvert stuttgart-regbez-latest.osm.pbf -b=8.78597,48.55525,8.98613,48.64040 --complete-ways -o=herrenberg.pbf
```

### 3. Run OTP locally:
* use port other than 8080
* remove the OSM data of Stuttgart area (otherwise it will be used too)
* run command from the same folder as the data
```
$ java -Xmx3G -jar otp-1.4.0-shaded.jar --build . --port 8801 --securePort 8802 --basePath .
```

**Comment by Beck-berry** [comment]
[Graph Builder](https://github.com/opentripplanner/OpenTripPlanner/wiki/graphbuilder)

**Comment by Beck-berry** [comment]
### Preprocessing the data according to [transportkollektiv's data-container](https://github.com/transportkollektiv/OpenTripPlanner-data-container/tree/hb)
1. `gulp osm:update` (takes up long)
2. `sudo gulp gtfs:dl`
3. `sudo gulp gtfs:fit`
4. `sudo gulp gtfs:filter`
5. `gulp gtfs:id`
6. `gulp router:buildGraph` (takes up long)

When building the graph, got lots of 'Area osm way <id> is not epsilon-valid' warnings. Can this cause any routing errors later?

7. `./deploy.sh` creates and runs a docker image, 1.03GB for HBG

### Run docker image
1. `docker images`
2. `docker run -d -p 8080:8801 <ImageID>`

![Screenshot_2019-10-24_12-13-40](https://user-images.githubusercontent.com/46535522/67476229-e5d46380-f657-11e9-83a2-df5d5c59f68a.png)
However localhost displays nothing.

**Comment by Beck-berry** [comment]
[result of docker inspect container command](https://github.com/mfdz/digitransit-ui/files/3770825/inspectContainer.txt)
On 172.17.0.1:8080 the list of the preprocessed and created files are available, so the container is running but there is no UI.

**Comment by Beck-berry** [comment]
### Run OTP with preprocessed data
0. move to the folder where the otp-shaded.jar file is
1. `$ wget -r http://localhost:8801/`
2. 
```
$ cd localhost\:8801/
$ unzip graph-hb-a0c7971f62251a3a1070652a3895c628557e1b62.zip
```
3. `$ java -Xmx3G -jar otp-1.4.0-shaded.jar --router hb --graphs localhost\:8801 --port 8000 --securePort 8001 --server --basePath .`

Error in the graph:
![Screenshot_2019-10-25_10-25-47](https://user-images.githubusercontent.com/46535522/67555658-006b1300-f712-11e9-8923-8202d2a4d36f.png)

**Comment by Beck-berry** [comment]
### Run OTP via IntelliJ
work on HSLDevCom/OpenTripPlanner master branch
1. ```mvn clean package -DskipTests``` --> creates target/otp-1.5.0-SNAPSHOT-shaded.jar
2. ```chmod u+x ./otp```
3. updated otp file so as to allow 8GB RAM usage
3. create graphs/hb/ folder tree with the following files: build-config.json, router-config.json, gtfs files, osm file
4. Build graph
![buildgraph_config](https://user-images.githubusercontent.com/46535522/71089171-923a4e00-21a0-11ea-9096-5446ef31306b.png)
5. Serve graph
![servegraph_config](https://user-images.githubusercontent.com/46535522/71089182-96ff0200-21a0-11ea-9c0e-3e182173a001.png)
