### ISSUE TITLE
Run WordPress offical image as first try

### ISSUE THREAD

**Issue by nandor-poka** [mfdz/digitransit-ui#5]
Try out Kubernetes by running the official WordPress container and see if that works. 
Estimate 2h.

**Comment by Beck-berry** [comment]
1. find the WordPress image: https://hub.docker.com/_/wordpress/
2. ```oc new-app wordpress``` --> Found Docker image 7dcb194 (22 hours old) from Docker Hub for "wordpress"
3. ```oc status```
4. "The connection has timeout."

**Comment by Beck-berry** [comment]
In the OKD console (via the browser) I got the following error when deploying the wordpress app:
"AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.9. Set the 'ServerName' directive globally to suppress this message
(13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80"

**Comment by Beck-berry** [comment]
Added files: /etc/apache2/conf-available
* ports.conf: "Listen 80"
* fqdn.conf: "ServerName localhost"
--> Opens localhost:80 correctly but still got an error

**Comment by nandor-poka** [comment]
> https://askubuntu.com/questions/256013/apache-error-could-not-reliably-determine-the-servers-fully-qualified-domain-n
> Added files: /etc/apache2/conf-available
> 
>     * ports.conf: "Listen 80"
> 
>     * fqdn.conf: "ServerName localhost"
> 
> 
> --> Opens localhost:80 correctly but still got an error
> 
> ![Screenshot_2019-09-05_09-21-58](https://user-images.githubusercontent.com/46535522/64320363-a6c25400-cfbe-11e9-9de5-9fcfecd0bd72.png)
> ![Screenshot_2019-09-05_09-25-37](https://user-images.githubusercontent.com/46535522/64320579-24865f80-cfbf-11e9-92fd-c89fcfe7ddb4.png)

fdqn = Fully qualified domain name -> something like ww.gerhardt.io servername localhost is not a valid FQDN,
also the error message says that the Servername directive shoudl be set that means there should be an option / attribute that is ServerName= <server name>
also binding to 0.0.0.0:80 means that it tries to bind the port 80 on **every** IP available on them machine. It may be better to specify a concrete IP to bind.

**Comment by Beck-berry** [comment]
Any changes in the files did nothing.

[Port forwarding](https://docs.okd.io/latest/dev_guide/port_forwarding.html) still didn't help.

**Comment by Beck-berry** [comment]
```oc new-project project1
oc tag --source="docker" hsldevcom/digitransit-ui dt-ui-test1:tip
oc new-app dt-ui-test1:tip
oc status```
--> uses port 8080

**Comment by Beck-berry** [comment]
https://kubernetes.io/docs/reference/kubectl/docker-cli-to-kubectl/
With 
1. ```oc run --image=wordpress wp-app --port=8080 --env="DOMAIN=cluster"```
2. ```oc expose deploymentconfig.apps.openshift.io/wp-app --port=8080 --name=wp-http```

the port in the description changed to 8080/tcp but the error remained the same: "(13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80"

To see the logs in local terminal: ```oc logs <podName> -c <appName>```
To get the pod's name: ```oc get pods```

**Comment by nandor-poka** [comment]
> https://kubernetes.io/docs/reference/kubectl/docker-cli-to-kubectl/
> With
> 
>     1. `oc run --image=wordpress wp-app --port=8080 --env="DOMAIN=cluster"`
> 
>     2. `oc expose deploymentconfig.apps.openshift.io/wp-app --port=8080 --name=wp-http`
> 
> 
> the port in the description changed to 8080/tcp but the error remained the same: "(13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80"
> 
> To see the logs in local terminal: `oc logs <podName> -c <appName>`
> To get the pod's name: `oc get pods`


port |   |   | The port that this container exposes.  If --expose is true, this is also the port used by the service that is created.
-- | -- | -- | --
This means that the port 8080 will be open in the container. But the container needs to open port 80.


hostport |   | -1 | The host port mapping for the container port. To demonstrate a single-machine container.
-- | -- | -- | --


also look at the description of expose....

**Comment by Beck-berry** [comment]
https://docs.openshift.com/container-platform/3.4/dev_guide/expose_service/expose_internal_ip_nodeport.html
https://kubernetes.io/docs/concepts/services-networking/service/

**Comment by Beck-berry** [comment]
Found a kind of tutorial for WP with Kubernetes but there is a command which does not work.
https://kubernetes.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/

**Comment by Beck-berry** [comment]
With [this tutorial](https://medium.com/@sarangrana/deploying-wordpress-web-application-with-mysql-in-kubernetes-d068c4683be7) I managed to run WP without the port error. I had to create new yaml files:
* PersistentVolume,
* MySQL Service, Persistent Volume Claim, Deployment
* WordPress Service, Persistent Volume Claim, Deployment

New problem is: not even one file can be opened -- permission denied.

**Comment by Beck-berry** [comment]
> New problem is: not even one file can be opened -- permission denied.

The solution was the give write permissions to the mount path folder (which is given in the wordpress deployment yaml file).

**Comment by Beck-berry** [comment]
To see all the infos about the pods: ```oc describe pods <podName>```

> > New problem is: not even one file can be opened -- permission denied.
> 
> The solution was the give write permissions to the mount path folder (which is given in the wordpress deployment yaml file).
> 
> New problem is: pod stucks in pending status: "pod has unbound PersistentVolumeClaims"

The permission problem only seemed to be solved, it came back after the second was solved.
![Screenshot_2019-09-10_10-52-57](https://user-images.githubusercontent.com/46535522/64599140-2bdfab80-d3b9-11e9-9149-2000eeec3f45.png)

**Comment by Beck-berry** [comment]
> With [this tutorial](https://medium.com/@sarangrana/deploying-wordpress-web-application-with-mysql-in-kubernetes-d068c4683be7) I managed to run WP without the port error. I had to create new yaml files:
>
>     * PersistentVolume, (important: you have to have admin permissions to this step: `oc login -u system:admin` or [add the user as admin](https://developers.redhat.com/blog/2017/12/04/customize-openshift-rbac-permissions/))
> 
>     * MySQL Service, Persistent Volume Claim, Deployment
> 
>     * WordPress Service, Persistent Volume Claim, Deployment

At the creation of WordPress' Deployment the container port has to be changed from 80.
Also the command ```oc status --suggest``` suggested another command which I run, and now everything works just fine.
