### ISSUE TITLE
Create Carpool "stations" layer UI

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/digitransit-ui#55]
Right now the stops and stations map layers correctly only display public transport legs. However, the same endpoint that returns these stops (encoded as protobuf) also returns the carpool "stops".

The file `Stops.js` contains the code for drawing those stops on the map and it filters out the carpool ones.

**Acceptance criteria**

- Add a point "Carpool stops" to the map layer selector
![Screenshot from 2020-02-18 13-55-19](https://user-images.githubusercontent.com/151346/74738066-6e55c000-5256-11ea-8c38-7c619d332818.png)

- Modify the existing code so that `Stops.js` also draws these stops on the map when the layer is selected.

**Comment by Beck-berry** [comment]
![Screenshot_2020-02-20_12-54-26](https://user-images.githubusercontent.com/46535522/74931597-3a0e0b00-53e0-11ea-8270-ced83c40e275.png)
![Screenshot_2020-02-20_12-54-43](https://user-images.githubusercontent.com/46535522/74931599-3aa6a180-53e0-11ea-846d-8861aa0331d4.png)

**Comment by leonardehrenfried** [comment]
@hbruch: if i remember correctly then you only want to display stops whose name starts with "P+M", like "P+M Parkplatz A81 Herrenberg". there is nothing in the id (or elsewhere in the JSON) that we can use to reliably identify those "larger" carpool stops.

or am i overlooking something?

**Comment by leonardehrenfried** [comment]
@meromisi @Beck-berry I now have the definitive specification: please only display carpooling stops if they start with the string `P+M`. This will filter out the vast majority of stops and only about 100 will be left.

To test that it really works you should move the map to https://www.openstreetmap.org/search?query=herrenberg#map=17/48.58072/8.90223

This is a designated carpool stop.

**Comment by leonardehrenfried** [comment]
![Screenshot from 2020-02-27 15-07-24](https://user-images.githubusercontent.com/151346/75452720-0d736980-5973-11ea-81a9-c0a1b568245e.png)
