### ISSUE TITLE
Fix display of "Walk X km" for carpool legs

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/digitransit-ui#58]
![Screenshot from 2020-02-15 21-14-10](https://user-images.githubusercontent.com/151346/74594632-e050be00-5038-11ea-8f72-96b7b4713d29.png)

In the screenshot above you can see that the UI describes carpool legs as "Walk X km".

This should of course be labeled "Carpool X km". In German that would be "X km mitfahren".

**Comment by hbruch** [comment]
What makes me wonder: why are there 3 carpool legs shown in the trip summary, but only one in the details?

**Comment by hbruch** [comment]
Instead of „Drive“ I‘d prefer „Carpool“ (I associate „drive“ with the driver role)

**Comment by leonardehrenfried** [comment]
Good point. I've updated the description.

**Comment by leonardehrenfried** [comment]
> What makes me wonder: why are there 3 carpool legs shown in the trip summary, but only one in the details?

I've figured it out: in the above screenshot the expanded view is not the expansion of the list item above. When you expand a collapsed route the collapsed view disappears.

![ezgif-3-169c0f94eb4c](https://user-images.githubusercontent.com/151346/74638539-602b7500-516c-11ea-9306-5acf9d2e05da.gif)

**Comment by leonardehrenfried** [comment]
![Screenshot from 2020-02-17 10-28-49](https://user-images.githubusercontent.com/151346/74640759-5f94dd80-5170-11ea-9877-a88737eaa25e.png)
![Screenshot from 2020-02-17 10-28-35](https://user-images.githubusercontent.com/151346/74640767-628fce00-5170-11ea-9655-467940000d79.png)

I've chosen the following translations:

- Carpool X km
- X km mitfahren

Not sure if "Fahrgemeinschaft X km" would be better. Any opinions, @hbruch ?
