### ISSUE TITLE
Use HSL based deploy script to deploy back-end

### ISSUE THREAD

**Issue by nandor-poka** [mfdz/digitransit-ui#6]
The official project has deploy scripts that can / could be used out of the box. Look up the repo for deploy scripts to find the right one and run it. Implement modifications if necessary.
If need more resources user ernie (ernie is a mobile workstation with 8 cores and 64G ram).
Estimation: 16h

**Comment by frankgerhardt** [comment]
We come back to OKD after Az is working

**Comment by hbruch** [comment]
Currently, we use a docker-compose setup. Closing this for now.
