### ISSUE TITLE
Add carpooling platform logos to UI

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/digitransit-ui#60]
![Screenshot from 2020-02-17 14-25-19](https://user-images.githubusercontent.com/151346/74661568-7f3ffc00-5198-11ea-8cac-c7b94706a554.png)

We would like to display the carpool platform logos in the carpool leg UI.

Check `CarLeg.js` for the code that displays this UI component. The leg contains an agency which can be used to select the correct logo.

Logo sources:
- https://www.fahrgemeinschaft.de/presse.php?int_tab=4
- https://www.mifaz.de/static/logo/mifaz_logo.svg

Hint: If you develop locally and want to use a carpool-enabled backend, you should add `API_URL=https://api.mih.mitfahren-bw.de/` to the command starting digitransit.

**Comment by leonardehrenfried** [comment]
@Beck-berry @meromisi Can you post a screenshot when you've added the icon?

**Comment by Beck-berry** [comment]
Mifaz:
![Screenshot_2020-02-18_12-34-25](https://user-images.githubusercontent.com/46535522/74736475-208b8880-5253-11ea-8ea0-e41466cb1d61.png)
Farhgemeinshaft:
![Screenshot_2020-02-18_13-26-12](https://user-images.githubusercontent.com/46535522/74736478-21bcb580-5253-11ea-9e32-2baafedb2c7e.png)

**Comment by leonardehrenfried** [comment]
@Beck-berry @meromisi 

I just spoke to Holger and he has the following requests:

- the logo should stay on the right hand side of "Details"
- move the logo down a few pixels so it aligns with the center line of the text
- the fahrgemeinschaft.de logo needs an additional logo next to it: https://upload.wikimedia.org/wikipedia/commons/8/8d/ADAC-Logo.svg as seen on https://mitfahren-bw.de/

**Comment by Beck-berry** [comment]
![Screenshot_2020-02-19_15-38-55](https://user-images.githubusercontent.com/46535522/74844688-1ee2c300-532e-11ea-9b23-1e1799962a85.png)
