### ISSUE TITLE
Create banner to tell the user that we are using matomo for tracking

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/digitransit-ui#61]
> Holger
> But that‘s a good point: legally, we have to display a cookie consent. Digitransit supports showing such messages already, we just need the relevant snippet

**Comment by Beck-berry** [comment]
![Screenshot_2020-02-20_10-25-24](https://user-images.githubusercontent.com/46535522/74919726-53588c80-53cb-11ea-9047-91642e32501a.png)
