### ISSUE TITLE
Add white background to carpool SVG in journey overview

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/digitransit-ui#63]
![Screenshot from 2020-02-20 13-08-50](https://user-images.githubusercontent.com/151346/74932468-354a5680-53e2-11ea-9f4f-f65aef1725c3.png)

If we add a white background, then it would become a little clearer what the icon means.

Not sure if it would be better to change the source SVG or do in CSS.

@Beck-berry Do you have an idea which is easier to do?

_Note_: You can find car pool routes with this link: https://mih.mitfahren-bw.de/reitti/T%C3%BCbingen%3A%3A48.5236164%2C9.0535531/Stuttgart%2C%20Stuttgart%3A%3A48.7784485%2C9.1800132?locale=de&modes=PUBLIC_TRANSPORT%2CCARPOOL&time=1582194123

**Comment by Beck-berry** [comment]
I think we should modify the SVG, because there are two icon ids in set: _icon_ and _icon-without-box_. The code is looking for the first one but yet we have the same SVG source under both ids.

**Comment by leonardehrenfried** [comment]
![Screenshot from 2020-02-20 13-35-18](https://user-images.githubusercontent.com/151346/74934166-dd155380-53e5-11ea-827a-bd3621d94c1d.png)

What would be even better if we did the same thing as the other modalities do: make the car white and put it on a green background.

Sorry for the late change.

**Comment by Beck-berry** [comment]
I think I am a mind-reader!

![Screenshot_2020-02-20_13-35-27](https://user-images.githubusercontent.com/46535522/74934173-e0104400-53e5-11ea-86f7-630b8a0150fe.png)

**Comment by Beck-berry** [comment]
![Screenshot_2020-02-20_14-27-28](https://user-images.githubusercontent.com/46535522/74937825-24eba900-53ed-11ea-9257-d349fe784150.png)

**Comment by hbruch** [comment]
Was fixed via #66
