### ISSUE TITLE
Create tooltips for modality icons in journey overview and details

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/digitransit-ui#65]
![Screenshot from 2020-02-20 13-35-18](https://user-images.githubusercontent.com/151346/74934273-1fd72b80-53e6-11ea-964f-c94628b254b9.png)

![Screenshot from 2020-02-20 13-36-57](https://user-images.githubusercontent.com/151346/74934257-1948b400-53e6-11ea-8901-51460b2b01a4.png)

We should have tooltips for the in the above views.

This view already does it:

![Screenshot from 2020-02-20 13-39-10](https://user-images.githubusercontent.com/151346/74934387-67f64e00-53e6-11ea-86fb-30b7139927cb.png)

if we have a line or bus name (like U34) then add that but for carpooling, walk, drive it should be the modality.

**Comment by Beck-berry** [comment]
Spoke with Holger and he'd like to add the tooltips to the carpool agency icons.

**Comment by Beck-berry** [comment]
![Screenshot_2020-02-21_14-31-59](https://user-images.githubusercontent.com/46535522/75038591-f2a67e00-54b6-11ea-817a-7eedbfbe3ad0.png)
