### ISSUE TITLE
No popup for some roadworks

### ISSUE THREAD

**Issue by hbruch** [mfdz/digitransit-ui#69]
For some roadworks, no popup is shown.

![image](https://user-images.githubusercontent.com/2187389/75138820-73e65680-56eb-11ea-88e8-04aa3dbccb1c.png)

**Comment by leonardehrenfried** [comment]
This happens because there is no selector row implemented for the roadworks map features.

Check how `SelectCovid19OpeningHoursRow.js` does it and implement the same for roadworks.

**Comment by Beck-berry** [comment]
![Screenshot_2020-04-30_10-23-36](https://user-images.githubusercontent.com/46535522/80688804-abe38e80-8acc-11ea-8bb0-8753f837fee9.png)

Would you like to see different icons depending on the type of the roadwork?
Also there are some duplications in the svg sprite file, I'll remove them.
