### ISSUE TITLE
More detail infos for parking lots

### ISSUE THREAD

**Issue by hbruch** [mfdz/digitransit-ui#71]
For the parkings popup, some more (optional) detail information should be provided:
* Opening hours
* Details-Link

Would be great if we could set the "closed" status in the ParkAPI if there are opening hours defined and time is out of the specified window. If status is closed, it should appear like zero lots available. If closing soon (e.g. in less than 30 minutes), we could render a hint "Schließt demnächst" and render like only a few places left.

For JS, there is [a tool to interpret the OSM opening hour string](https://openingh.openstreetmap.de/evaluation_tool/?setLng=en), for [Python](https://pypi.org/project/osm-humanized-opening-hours/) as well.

Data for opening hours/links will be provided by Herrenberg. For now, for Bronntor the following infos can be used:

Details: https://stadtwerke.herrenberg.de/oepnv-parken/parken/sicher-und-zentral-parken/parkhaeuser-und-parkgebuehren/bronntor-tiefgarage/
Opening hours:[ Mo-Fr 7:30-22:00; Sa 7:30-18:00; PH off](https://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo-Fr%207%3A30-22%3A00%3B%20Sa%207%3A30-18%3A00%3B%20PH%20off&lat=48.7769&lon=9.1844&mode=0&DATE=1357161660000)

Both infos should be added to ParkAPI as custom extensions, which we will provide a Pull request for later on.

**Comment by leonardehrenfried** [comment]
The data should be added here: https://github.com/mfdz/thingsboard-to-parkapi/blob/master/parking_lots.geojson

**Comment by leonardehrenfried** [comment]
For the opening hours please use the property name `openingHours`.

**Comment by leonardehrenfried** [comment]
I think the specification of this feature needs to be revisited. 

https://stadtwerke.herrenberg.de/oepnv-parken/parken/sicher-und-zentral-parken/parkhaeuser-und-parkgebuehren/bronntor-tiefgarage/ only talks about when you have to pay to get in but it doesn't say anything about opening hours.

The opening hours on the right hand side of the page refers AFAICT to the office, not the car park itself.

@hbruch Can you clarify this with herrenberg?

**Comment by leonardehrenfried** [comment]
What we could do though is to display the paid times (rather than the opening hours) in the popup.

**Comment by Beck-berry** [comment]
![Screenshot_2020-02-28_14-16-42](https://user-images.githubusercontent.com/46535522/75756391-dd401800-5d30-11ea-9c8c-a2aba7894cf7.png)
![Screenshot_2020-03-03_09-24-37](https://user-images.githubusercontent.com/46535522/75756393-ddd8ae80-5d30-11ea-8532-0eab50ff5b73.png)

**Comment by Beck-berry** [comment]
![Screenshot_2020-03-03_12-17-42](https://user-images.githubusercontent.com/46535522/75770821-066ca280-5d49-11ea-9b03-ce14a2ac0b18.png)

**Comment by leonardehrenfried** [comment]
I like the latter better but I think @hbruch should take a look and make a decision as he's has more of an idea what the end result should be.

**Comment by Beck-berry** [comment]
If parking lot is closing in less than 30 minutes:
![Screenshot_2020-03-05_11-03-12](https://user-images.githubusercontent.com/46535522/75970884-4e1e3600-5ed1-11ea-9d50-b078c9fdd817.png)
If parking lot is closed now:
![Screenshot_2020-03-05_11-03-40](https://user-images.githubusercontent.com/46535522/75970887-4eb6cc80-5ed1-11ea-939b-d1f7791b82b3.png)

**Comment by leonardehrenfried** [comment]
I like it, but again @hbruch should have the final word as he knows what the client wants.

**Comment by Beck-berry** [comment]
Added "Closes soon" motification to popup:

![Screenshot_2020-03-05_14-30-04](https://user-images.githubusercontent.com/46535522/75986170-dd394700-5eed-11ea-87d5-c66e8d48569f.png)
![Screenshot_2020-03-05_14-31-14](https://user-images.githubusercontent.com/46535522/75986241-fe019c80-5eed-11ea-996f-2ccab61fd06f.png)

**Comment by leonardehrenfried** [comment]
Please rebase this branch onto master and use the new `OSMOpeningHours` component and remove the heavy library.
