### ISSUE TITLE
Display blue dots for parking lots at a lower zoom level

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/digitransit-ui#72]
Right now if you zoom out the dots are black, even though the icons are blue:

![Screenshot from 2020-02-27 11-59-07](https://user-images.githubusercontent.com/151346/75438769-d5f7c380-5958-11ea-8502-35a2ef3df8f2.png)

They should be blue though.

**Comment by Beck-berry** [comment]
![Screenshot_2020-02-27_12-33-24](https://user-images.githubusercontent.com/46535522/75441127-5ddfcc80-595d-11ea-8976-3439db3c0f32.png)
