### ISSUE TITLE
Route not found caused by isolated highway=track ways

### ISSUE THREAD

**Issue by hbruch** [mfdz/digitransit-ui#79]
No car trip found for e.g. https://pilot.mobil-in-herrenberg.de/reitti/Seestraße%2019%2F1%2C%20Herrenberg%3A%3A48.59724504108028%2C8.868606090545656/Tübinger%20Straße%2C%20Herrenberg%3A%3A48.58529481682537%2C8.888196945190431?arriveBy=false&modes=CAR_PARK&time=1583159635

**Comment by leonardehrenfried** [comment]
As you can see from the URL, you've selected CAR_PARK only.

I guess we would expect our `ComparingGraphPathFinder` to switch to `CAR`?

**Comment by leonardehrenfried** [comment]
May I ask how you managed to create this route?

If I move the destination pin only a little bit onto the road, then it works: https://pilot.mobil-in-herrenberg.de/reitti/Seestra%C3%9Fe%2019%2F1%2C%20Herrenberg%3A%3A48.59724504108028%2C8.868606090545656/T%C3%BCbinger%20Stra%C3%9Fe%2C%20Herrenberg%3A%3A48.58524513659796%2C8.888137936592104?arriveBy=false&modes=CAR_PARK&time=1583159635

**Comment by leonardehrenfried** [comment]
I'm speculating that it could be because of the destination being on the grass:

![Screenshot from 2020-03-02 16-40-43](https://user-images.githubusercontent.com/151346/75691655-a4f2f800-5ca4-11ea-9537-d48194f24776.png)

**Comment by hbruch** [comment]
In Germany, `highway=track` usually is assigned to agricultural ways where motor_vehicles are usually not allowed. As OSM data often lacks this explicit mode tag, we should allow `highway=track` per default only for pedestrians and bicycles. To avoid interference with OTP standard behavior which might be appropriate elsewhere, we only apply this change to the `GermanyWayPropertySetSource`.

**Comment by leonardehrenfried** [comment]
Works on staging: https://mih.mitfahren-bw.de/reitti/Seestra%C3%9Fe%2019%2F1%2C%20Herrenberg%3A%3A48.59724504108028%2C8.868606090545656/T%C3%BCbinger%20Stra%C3%9Fe%2C%20Herrenberg%3A%3A48.58529481682537%2C8.888196945190431?arriveBy=false&modes=CAR_PARK&time=1583159635
