### ISSUE TITLE
Run WordPress offical image as first try

### ISSUE THREAD

**Issue by nandor-poka** [mfdz/digitransit-ui#8]
Try out Kubernetes in the Azure cloud by running the official WordPress container and see if that works.
Estimate 2h.

**Comment by meromisi** [comment]
- use the official WP image from hub.docker.com/_/wordpress
- for now, it could be a shell script
- all, or as much as possible, from command line, not from web ui
- login
- create kubernetes cluster
- pull the WP image into the k8s
- lauch
- check that it is running
- nake a script to tear down averything

At the very end
- notebook that does the complete setup from zero (and also the tear down)

estimate 8h

**Comment by meromisi** [comment]
Successfully deployed wordpress official image to AKS. 
Before you begin install Azure-CLI and kubectl from the links below.
Azure-CLI: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest
kubectl: https://kubernetes.io/docs/https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latesttasks/tools/install-kubectl/

commands i used:

az login

az group create --name myResourceGroup --location westeurope

az aks create \
    --resource-group myResourceGroup \
    --name myAKSCluster \
    --node-count 2 \
    --enable-addons monitoring \
    --generate-ssh-keys  

// takes up to 20 mins

(az aks install-cli)

az aks get-credentials --resource-group   --name myAKSCluster

kubectl get nodes

cat <<EOF >./kustomization.yaml
secretGenerator:
- name: mysql-pass
  literals:
  - password=wordpress
EOF


curl -LO https://k8s.io/examples/application/wordpress/mysql-deployment.yaml

curl -LO https://k8s.io/examples/application/wordpress/wordpress-deployment.yaml

!important! : change version of wordpress to the latest(now: 5.2.3) in the wordpress yaml file 

cat <<EOF >>./kustomization.yaml
resources:
  - mysql-deployment.yaml
  - wordpress-deployment.yaml
EOF

kubectl apply -k ./

//kubectl get secrets - optional (just for checking)

//kubectl get pvc - optional (just for checking)

kubectl get pods // takes 4-5 mins

kubectl get services wordpress takes 3 mins

DELETE: kubectl delete -k ./

DELETE: az group delete --name myResourceGroup --yes //takes up to 15mins
