### ISSUE TITLE
Translate Finnish URL endpoints into German

### ISSUE THREAD

**Issue by hbruch** [mfdz/digitransit-ui#80]
URLs contain some Finish endpoints. To comfort the main target audience, we should switch to  German here.

`app/util/path.js` contains the definitions:

```
export const TAB_NEARBY = 'lahellasi';
export const TAB_FAVOURITES = 'suosikit';
export const PREFIX_ROUTES = 'linjat';
export const PREFIX_STOPS = 'pysakit';
export const PREFIX_TERMINALS = 'terminaalit';
export const PREFIX_ITINERARY_SUMMARY = 'reitti';
```

**Comment by leonardehrenfried** [comment]
```
export const TAB_NEARBY = 'indernaehe';
export const TAB_FAVOURITES = 'gespeichertesuchen';
export const PREFIX_ROUTES = 'routen';
export const PREFIX_STOPS = 'haltestellen';
export const PREFIX_TERMINALS = 'busbahnhoefe';
export const PREFIX_ITINERARY_SUMMARY = 'reiseplan';
```

**Comment by meromisi** [comment]
So do we need to simply switch to german or leave it as default and only switch to german when config is hb?

**Comment by leonardehrenfried** [comment]
Looking at the [Helsinki router](https://reittiopas.hsl.fi/reitti/Kampinkuja%201%2C%20Helsinki%3A%3A60.169022%2C24.931691/main%20station%3A%3A60.25095%2C25.01076?locale=en&time=1586167194) the URLs always stay the same, even when switching the language.
