### ISSUE TITLE
Add CyclOSM as default background for cycling mode

### ISSUE THREAD

**Issue by hbruch** [mfdz/digitransit-ui#82]
If cycling is chosen as mode, the background map should be changed to cyclosm:
<img width="708" alt="image" src="https://user-images.githubusercontent.com/2187389/75906660-516cdf80-5e47-11ea-86e4-fcee33d89c41.png">
When cyclosm map is shown as background, a "[CyclOSM](https://www.cyclosm.org/) & [OSM-FR](https://www.openstreetmap.fr)" attribution should dynamically be added.

**Comment by Beck-berry** [comment]
There are tiny white lines between the tiles at all zoom levels.
![Screenshot_2020-03-05_13-05-20](https://user-images.githubusercontent.com/46535522/75980149-34391f00-5ee2-11ea-9eab-de9b5159776f.png)

Is there a way to resize the tiles?

**Comment by leonardehrenfried** [comment]
![Screenshot from 2020-03-05 17-40-20](https://user-images.githubusercontent.com/151346/76003519-75442a00-5f08-11ea-90e1-25a6124888e9.png)

Actually, it looks ok for me.

Which browser is this?

**Comment by Beck-berry** [comment]
Mozilla.

**Comment by leonardehrenfried** [comment]
Please use the new mapMode infrastructure for this feature. Should be pretty easy then.
