### ISSUE TITLE
Layout corrupted when starting with CONFIG=hb yarn run start

### ISSUE THREAD

**Issue by hbruch** [mfdz/digitransit-ui#85]
Since commit e2061474aa8b6ee the layout is corrupted when starting via CONFIG=hb yarn run start:

<img width="689" alt="grafik" src="https://user-images.githubusercontent.com/2187389/76167619-40cea900-6168-11ea-8095-d0007daecae9.png">

This should not occur.

**Comment by leonardehrenfried** [comment]
In case you're wanting to do local development, I use the following command:

```
CONFIG=hb \
  MAP_URL=$URL \
  MAP_KEY=$KEY \
    yarn run dev
```

The command you're running is (seems?) for production use and looking at the Dockerfile I see a few commands you can try running beforehand: https://github.com/mfdz/digitransit-ui/blob/master/Dockerfile#L31-L35

Without having tested it, I would say that `yarn run build` is a promising candidate.

**Comment by hbruch** [comment]
Before the cited commit it worked as described above. I‘m using the default wikimedia map server which does not require a map_key. This should still be possible. Are we required to split map_url and map_key? Or can they be provided as a single map_url (which than might have additional params, if required)?

**Comment by leonardehrenfried** [comment]
`MAP_KEY` is optional. If it isn't then it's a bug.

I also just wanted to use a single URL but digitransit manipulates the URL in ways which made this impossible. At least I gave up getting it to work.

Not sure about your specific setup but my hunch is that your CSS files need to be rebuild. 

Both staging and production use the command you posted. Do they look broken in your browser?

**Comment by hbruch** [comment]
That might be. Closing this issue, sorry for bothering you...
