### ISSUE TITLE
Move the carpool icon "up one level"

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/digitransit-ui#89]
Right now if you want to search for a carpool route, it's a little complicated to get to it.

![Screenshot from 2020-03-10 14-22-05](https://user-images.githubusercontent.com/151346/76316238-8ad79c00-62da-11ea-938b-1511e6160b8a.png)

We want to add an icon to the first line of icons:

![Screenshot from 2020-03-10 14-23-18](https://user-images.githubusercontent.com/151346/76316336-b8bce080-62da-11ea-9264-3440366b658d.png)

It should be the carpool icon and its modes should be `WALK, CARPOOL`.

If you select this icon then the second line of icons should disappear.

**Comment by Beck-berry** [comment]
![Screenshot_2020-03-11_12-15-52](https://user-images.githubusercontent.com/46535522/76411559-59220c00-6392-11ea-8758-f21a0f230d0e.png)
